# Generated by Django 5.0.6 on 2024-08-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signname', models.TextField()),
                ('signemail', models.EmailField(max_length=254)),
                ('signpass', models.TextField()),
            ],
        ),
    ]
